// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMlxFaB9rZ5kjWkN0T6dIuG-xBRO61l0c',
    appId: '1:427263509301:web:3a65008852d7fc458c827c',
    messagingSenderId: '427263509301',
    projectId: 'finance-analyzers',
    authDomain: 'finance-analyzers.firebaseapp.com',
    storageBucket: 'finance-analyzers.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEn5ttKFwrr6QOBZgvnIHnLi5qgyKymCs',
    appId: '1:427263509301:android:e71e319a46f2f24e8c827c',
    messagingSenderId: '427263509301',
    projectId: 'finance-analyzers',
    storageBucket: 'finance-analyzers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOu0NIV7KnlbD4KtCCXzvHKsOQ1El2rH0',
    appId: '1:427263509301:ios:e2c76e79656481f88c827c',
    messagingSenderId: '427263509301',
    projectId: 'finance-analyzers',
    storageBucket: 'finance-analyzers.firebasestorage.app',
    iosBundleId: 'com.example.financeAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOu0NIV7KnlbD4KtCCXzvHKsOQ1El2rH0',
    appId: '1:427263509301:ios:e2c76e79656481f88c827c',
    messagingSenderId: '427263509301',
    projectId: 'finance-analyzers',
    storageBucket: 'finance-analyzers.firebasestorage.app',
    iosBundleId: 'com.example.financeAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMlxFaB9rZ5kjWkN0T6dIuG-xBRO61l0c',
    appId: '1:427263509301:web:997f233ce2bb98cc8c827c',
    messagingSenderId: '427263509301',
    projectId: 'finance-analyzers',
    authDomain: 'finance-analyzers.firebaseapp.com',
    storageBucket: 'finance-analyzers.firebasestorage.app',
  );

}